#include "..\common.hpp"

ADD_LOADOUT("MISFIT_CIVILIAN_1",				"MISFIT_CIVILIAN\MISFIT_CIVILIAN_1.sqf")
ADD_LOADOUT("MISFIT_CIVILIAN_Militant_1",	"MISFIT_CIVILIAN\MISFIT_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("MISFIT_CIVILIAN_Saboteur_1",	"MISFIT_CIVILIAN\MISFIT_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("MISFIT_PLAYER_1",				"MISFIT_CIVILIAN\MISFIT_PLAYER_1.sqf")
ADD_LOADOUT("MISFIT_GUER_1",	"MISFIT_CIVILIAN\MISFIT_GUER_1.sqf")