#include "..\..\common.hpp"

ADD_LOADOUT("BRIT_POLICE_1",		"BRIT_POLICE\Police\BRIT_POLICE_(1).sqf")
ADD_LOADOUT("BRIT_POLICE_2",		"BRIT_POLICE\Police\BRIT_POLICE_(2).sqf")
ADD_LOADOUT("BRIT_POLICE_3",		"BRIT_POLICE\Police\BRIT_POLICE_(3).sqf")
ADD_LOADOUT("BRIT_POLICE_4",		"BRIT_POLICE\Police\BRIT_POLICE_(4).sqf")
ADD_LOADOUT("BRIT_POLICE_5",		"BRIT_POLICE\Police\BRIT_POLICE_(5).sqf")
ADD_LOADOUT("BRIT_POLICE_6",		"BRIT_POLICE\Police\BRIT_POLICE_(6).sqf")
ADD_LOADOUT("BRIT_POLICE_7",		"BRIT_POLICE\Police\BRIT_POLICE_(7).sqf")
ADD_LOADOUT("BRIT_POLICE_8",		"BRIT_POLICE\Police\BRIT_POLICE_(8).sqf")
ADD_LOADOUT("BRIT_POLICE_9",		"BRIT_POLICE\Police\BRIT_POLICE_(9).sqf")
ADD_LOADOUT("BRIT_POLICE_10",		"BRIT_POLICE\Police\BRIT_POLICE_(10).sqf")


