#include "..\..\common.hpp"

ADD_LOADOUT("US_POLICE_1",		"US_POLICE\Police\US_POLICE_(1).sqf")
ADD_LOADOUT("US_POLICE_2",		"US_POLICE\Police\US_POLICE_(2).sqf")
ADD_LOADOUT("US_POLICE_3",		"US_POLICE\Police\US_POLICE_(3).sqf")
ADD_LOADOUT("US_POLICE_4",		"US_POLICE\Police\US_POLICE_(4).sqf")
ADD_LOADOUT("US_POLICE_5",		"US_POLICE\Police\US_POLICE_(5).sqf")
ADD_LOADOUT("US_POLICE_6",		"US_POLICE\Police\US_POLICE_(6).sqf")
ADD_LOADOUT("US_POLICE_7",		"US_POLICE\Police\US_POLICE_(7).sqf")
ADD_LOADOUT("US_POLICE_8",		"US_POLICE\Police\US_POLICE_(8).sqf")


