#include "..\common.hpp"

ADD_LOADOUT("IRA_CIVILIAN_1",				"IRISH_CIVILIAN\IRA_CIVILIAN_1.sqf")
ADD_LOADOUT("IRA_CIVILIAN_Militant_1",	"IRISH_CIVILIAN\IRA_CIVILIAN_Militant_1.sqf")
ADD_LOADOUT("IRA_CIVILIAN_Saboteur_1",	"IRISH_CIVILIAN\IRA_CIVILIAN_Saboteur_1.sqf")
ADD_LOADOUT("IRA_PLAYER_1",				"IRISH_CIVILIAN\IRA_PLAYER_1.sqf")
